# https://github.com/sea-bass/turtlebot3_behavior_demos/blob/main/docker-compose.yaml
include:
  - base-compose.yml
  
  # ROS2 Jazzy  
  - compose_files/jazzy-dev-compose.yml
  # ROS2 Humble  
  - compose_files/humble-dev-compose.yml