# https://github.com/sea-bass/turtlebot3_behavior_demos/blob/main/docker-compose.yaml
include:
  - base/base-compose.yml
  - dev/dev-compose.yml
  # sensors
  - sensors/realsense-ros/realsense-compose.yml
