services:
  sctebot2_overlay:
    extends: 
      file: jazzy-base-compose.yml
      service: jazzy_overlay
    container_name: sctebot2_overlay
    image: sctebot2_overlay:latest
    build:
      context: ../
      dockerfile: docker_files/Dockerfile.sctebot2
      target: sctebot2_overlay

  sctebot2_description_node:
    extends: sctebot2_overlay
    container_name: sctebot2_description_node
    image: sctebot2_description_node:latest
    build:
      context: ../
      dockerfile: docker_files/Dockerfile.sctebot2
      target: sctebot2_description_node
    volumes:
      - ../../sctebot2:/sctebot2_ws/src:rw
      # TODO: copy other descriptions into the src folder?
    command: sleep infinity